train data len :  28266
validation data len :  7067
74120
start self supervised learning
start classification learning
  0%|                                                                                                                                 | 0/2 [00:00<?, ?it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  2.01it/s]

[epoch : 0]: 100%|██████████████████████████████████████████████████████████████████████████████████| 7/7 [00:05<00:00,  1.34batch/s, acc=0.540, loss=0.897]
 50%|████████████████████████████████████████████████████████████▌                                                            | 1/2 [00:00<00:00,  1.81it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.88it/s]
Traceback (most recent call last):
  File "train.py", line 285, in <module>
    train(model, train_dataloader, val_dataloader, model_args, data_args, device)
  File "train.py", line 195, in train
    early_stopping(val_loss, model)
  File "train.py", line 48, in __call__
    self.save_checkpoint(val_loss, model)
  File "train.py", line 63, in save_checkpoint
    torch.save(model.state_dict(), self.path)
  File "/opt/conda/envs/lightweight/lib/python3.7/site-packages/torch/serialization.py", line 361, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "/opt/conda/envs/lightweight/lib/python3.7/site-packages/torch/serialization.py", line 229, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/envs/lightweight/lib/python3.7/site-packages/torch/serialization.py", line 210, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './model/checkpoint.pt'